[theme]
primaryColor = "#4ECDC4"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[server]
headless = true
# Trigger redeploy Sat Apr  4 19:53:49     2026
